version: '3.1'

networks:
  kafka1:
    driver: "bridge"

# add to your local /etc/hosts
# 127.0.0.1 kafka-1
# 127.0.0.1 zookeeper-1

services:

  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888
    networks:
      - kafka1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-1:
    container_name: kafka-1
    ports:
      - 9092:9092
    image: confluentinc/cp-kafka:5.5.1
    links:
      - zookeeper-1
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka1